package:  
  name: flexflow
  version: "1.0"

source:
  git_url: https://github.com/flexflow/FlexFlow.git
  git_rev: 223e38c2f5c4c827adc829d8b02796dc65b6b623

build:
  number: 0

requirements:
  build:
    - make
    - git
    - zlib
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cffi
  run:
    - cffi
    - numpy
    - python
    - zlib
