package:
  name: "flexflow"
  version: "1.0"

source:
  git_rev: ffconda
  git_url: https://github.com/eddy16112/FlexFlow.git

build:
  number: 0

requirements:
  build:
    - make
    - git
    - zlib
    - protobuf
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cffi
  run:
    - cffi
    - numpy
    - python
    - zlib
